spring:
  application:
    name: edu-nexus-graphql

  graphql:
    path: /graphql
    graphiql:
      enabled: true
      path: /graphiql
    schema:
      inspection:
        enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://edu-nexus-discovery:8000/eureka/
    registerWithEureka: true
    fetchRegistry: true

server:
  port: 8006

grpc:
  client:
    edu-nexus-playback-service:
      address: 'discovery:///edu-nexus-playback-service'
      enable-keep-alive: true
      keep-alive-without-calls: true
      negotiation-type: plaintext
    edu-nexus-payment-service:
      address: 'discovery:///edu-nexus-enrollment-service'
      enable-keep-alive: true
      keep-alive-without-calls: true
      negotiation-type: plaintext
    edu-nexus-enrollment-service:
      address: 'discovery:///edu-nexus-enrollment-service'
      enable-keep-alive: true
      keep-alive-without-calls: true
      negotiation-type: plaintext

