### Create User 1
POST http://localhost:8080/users
Content-Type: application/json

{
  "name": "testUser3",
  "email": "edu-nexus3@example.com",
  "password": "nexus"
}

### Generate Token
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "edu-nexus3@example.com",
  "password": "nexus"
}

> {% client.global.set("authToken", response.body.token); %}

### Get User Login Histories
GET http://localhost:8080/users/1866282988690608128/login-histories

### Verify Token
POST http://localhost:8080/auth/verify-token
Content-Type: application/json

{
  "token": "{{authToken}}"
}

### Refresh Token
POST http://localhost:8080/auth/refresh-token
Content-Type: application/json

{
  "token": "{{authToken}}"
}