### Create User 1
POST http://localhost:8080/users
Content-Type: application/json

{
  "name": "Test User1",
  "email": "edu.nexus1@example.com",
  "password": "nexus"
}

### Create User 2
POST http://localhost:8080/users
Content-Type: application/json

{
  "name": "Test User2",
  "email": "edu.nexus2@example.com",
  "password": "edu"
}

> {% client.global.set("userId", 1866277254078795776); %}


### Get User by ID
GET http://localhost:8080/users/1866277254078795776
// GET http://localhost:8080/users/1866277280532271104

> {% client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    }); %}

### Get User Login Histories
GET http://localhost:8080/users/1866277254078795776/login-histories

### Change Password
POST http://localhost:8080/users/1866277254078795776/password-change
Content-Type: application/json

{
  "oldPassword": "neff",
  "newPassword": "nexus"
}

