server:
  port: 8000

spring:
  application:
    name: edu-nexus-discovery

eureka:
  instance:
    hostname: localhost
    registry:
      default-open-for-traffic-count: 1 # 0으로 설정한 경우 서버 Replication 활성화 가능. (디폴트 : 1)
  client:
    register-with-eureka: true # 레지스트리에 자신을 등록하지에 대한 여부 (디폴트 true)
    fetch-registry: true # 레지스트리에 있는 정보를 가져올지에 대한 여부 (디폴트 true), 30초마다 Eureka client가 유레카 레지스트리 변경사항 여부 재확인
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    region: default

  # Renews Threshold => 분당 heartbeat 수 (기본값 30초) * Instance 수 + Spring 에서 구성하는 최소 Instance 수 (1) * renewal-percent-threshold 값 계산 후 반올림을 한다.
  # ex: 2 * 1 + 1 * 0.85 = 3
  # Renews (last min) => 분당 heartbeat 수 (기본값 30초) * Instance 수
  # ex: 2 * 1 = 2
  server:
    enable-self-preservation: true # 일시적인 네트워크 장애로 인한 서비스 해제 막기 위한 자기보호 모드 (운영에서는 true 권장)
    renewal-percent-threshold: 0.85
