server:
  port: 8000

spring:
  application:
    name: edu-nexus-discovery

eureka:
  instance:
    hostname: localhost
    registry:
      default-open-for-traffic-count: 1 # 0?? ??? ?? ?? Replication ??? ??. (??? : 1)
  client:
    register-with-eureka: false # ?????? ??? ????? ?? ?? (??? true)
    fetch-registry: false # ?????? ?? ??? ????? ?? ?? (??? true), 30??? Eureka client? ??? ????? ???? ?? ???
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    region: default

  # Renews Threshold => ?? heartbeat ? (??? 30?) * Instance ? + Spring ?? ???? ?? Instance ? (1) * renewal-percent-threshold ? ?? ? ???? ??.
  # ex: 2 * 1 + 1 * 0.85 = 3
  # Renews (last min) => ?? heartbeat ? (??? 30?) * Instance ?
  # ex: 2 * 1 = 2
  server:
    enable-self-preservation: true # ???? ???? ??? ?? ??? ?? ?? ?? ???? ?? (????? true ??)
    renewal-percent-threshold: 0
